### PR TITLE
Proposal to merge @thangngoc89's migration to Dune and XXH3

### PR DESCRIPTION
**Pull request by LasseBlaauwbroek**
With permission of @thangngoc89 and @314eter, I'd like to upgrade the version of `ocaml-xxhash` in the opam repository so that it supports xxh3. If you'd like, I'm happy to submit a new package to to opam if you could merge this and create a new release tag.

### CODE REVIEW

**Comment by 314eter** [comment]
Done

**Comment by LasseBlaauwbroek** [comment]
Thanks @314eter, but note that PR #2 only included the Dune migration, not the addition of XXH3. So if @thangngoc89 agrees with that, it would be great if the `xxh3` branch of this PR could also be merged.

**Comment by LasseBlaauwbroek** [comment]
Oh, never mind, I see that I'm mistaken. Great. All that's needed now is to create a tag and release to the opam repo. Could you create a tag? If you'd like I can submit the package.

**Comment by 314eter** [comment]
I merged #2 first, and then this PR had merge conflicts, so I had to merge it manually.

I create a tag.

**Comment by thangngoc89** [comment]
Hey sorry for late response. It has been awhile since I worked with OCaml. If I remember correctly, I think that XXH3 isn't done. It segfaults if you try to call the function (probably because of my inexperience in working with C++ FFI).
However, the dune builder part is thoroughly tested.

**Comment by LasseBlaauwbroek** [comment]
I did confirm that there were some issues (not a segfault, but some strange linking problems on some platforms due to the Dune build). I submitted #4, which should fix these problems.

**Comment by thangngoc89** [comment]
@LasseBlaauwbroek thank you. I appreciated that. I can't even remember why I needed xxh3 binding for in my previous project.

**Pull request closed without merging**
